### PR TITLE
Implement editor.action.joinLines for 'J' key

### PR DESCRIPTION
**Pull request by nealot**
I don't know how to clear the selection after :(

### CODE REVIEW

**Comment by jpotterm** [comment]
The reason I didn't implement the `J` command is that VSCode natively supports joining lines. Just do `Ctrl+j` (or "Join Lines" from the command palette).

**Comment by nealot** [comment]
Oh okay. Is there a particular reason why you chose not to implement some vim keys that have native vscode replacements? Is it just a personal preference?

**Comment by jpotterm** [comment]
And there are several reasons I want to avoid duplicating native functionality where possible. One is to keep the code base small and easy to work with. Vim has a lot of functionality and implementing things that VSCode already does could be a big task. Another is that it's nice to be used to the native way of doing things in case you decide you don't need the vim extension anymore or you want to switch to a different vim extension. That way you know exactly what the extension is doing for you. And a final reason is that it makes it easier to learn the extension. The fewer commands in the documentation, the easier it is to read and understand them.

**Comment by nealot** [comment]
Well, it really depends what kind of audience you want to attract: In its current state, I think this extension will be great for VSCode users who want to try Vim keybindings without completely getting lost in the documentation. However, this audience doesn't seem to make the majority of users looking for a Vim extension since these people are usually those who have experience with vim.

I think if the focus of this project shifted to highlighting its performance improvements it would become vastly superior to other Vim extensions. I mean, the reason I switched from vscodevim was because this extension was way smoother to work with! I've tried all of the other emulators and this is by far the most performant. I haven't actually run any benchmarks but I can definitely notice reduced CPU usage and typing latency.

Right now, though, it seems like anyone who wants to have some basic vim command has to fork the repo and add it themselves. This result completely conflicts with the original purpose of the extension to be simple. For instance, why is "r" replacing "d"? And why does "s" seem to initiate visual mode? If I wanted to get rid of these bindings to match the original Vim I would have to modify the code myself which only introduces complexity. Other than that, I would have to adjust my preferences to match yours.

Anyways, what I'm trying to say is that this extension while adhering to the principle of "being simple" is kind of too opinionated for experienced Vim users who just want the fastest Vim extension. If we managed to emulate more vim features, we could demonstrate how at the cost of losing really obscure vim actions we can have a really fast and solid keybinding system that beats the alternatives.

Overall, this is a great extension and I really appreciate you making it public but it lacks some important vim keys that a lot vim users have grown to rely on. I understand why you want to keep the features to a minimum and notice the disclaimer in the README, but I just wanted to point out some things that might discourage potential users.

**Comment by jpotterm** [comment]
Very good points and well said! I completely agree. This extension is very opinionated and my original goal wasn't really to replace VSCodeVim or to attract as many users as possible. I basically just wrote the extension for myself and then decided to open source it in case other people found it useful.

I guess this extension actually has two goals. One is the performance improvements (that you mentioned above). The architecture uses the native VSCode selection model which gives it very minimal overhead.

The other goal was to try to make a version of vim with a minimal feature set. This was for two reasons. Mostly it was to make it practical for one person (me) to implement it in a reasonable amount of time. But also I was curious to see if there were vim features that weren't really necessary for the core experience. As a bonus I think this will make it easier to learn for non-vim people, but as you said, this probably isn't the majority of people who are looking for a vim extension. One of the things that I thought might be unnecessary is vim's register system. All non-vim users out there use a single register: the operating system clipboard, and that seems to work fine for them. But if you have just a single register, you really don't want `d` to modify it because you can no longer yank into a different register to preserve your yank. So I stopped `d` from modifying the register and then added a new `r` command (essentially cut) for the rarer cases when you want to delete and yank at the same time. I think this gives a pretty good alternative to implementing the whole register system of vim. And I tried to think through all of vim's features this way.

To some extent these two goals go hand in hand. For example, the reason VSCodeVim's performance is so bad is that they're not willing to deviate from any of vim's behavior which means they have to do a lot of hacks to get VSCode to act that way. But there is definitely a middle ground where you could deviate only slightly from vim's behavior and get nearly all the performance improvements of this extension while keeping things as close as possible to vim's behavior. For example, I think you could add back vim's register system without losing any performance. I'll have to think about this more, but at the moment I think I want to continue the current direction of this extension. But if anyone wants to fork this extension and make the experience much closer to vim's while keeping the performance improvements I definitely think it would be useful to a lot of people. Also, maybe I should make the readme clearer about how opinionated this extension is.

Anyway, I hope that makes sense. If not, let me know. Thanks for the great discussion so far, and I'm happy to discuss it more.

**Pull request closed without merging**
